# Build stage
FROM golang:1.24 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN go build -o main .

# Final stage (runtime environnement)
FROM ubuntu:latest
WORKDIR /app

COPY --from=builder /app/main .
COPY pkg ./pkg
RUN mkdir -p app/repository



EXPOSE 8080
CMD ["./main"]
