# Build stage
FROM golang:1.24 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY main.go .
COPY internal ./internal
COPY pkg ./pkg

RUN go build -o main ./

# Final stage (runtime environnement)
FROM alpine:latest
WORKDIR /app

COPY --from=builder /app/main ./main

# metadata,
LABEL maintainer="mennaas | abalouri | abaid | ranniz | ychatoua | azraji"
LABEL version="1.0"
LABEL description="Social Network"
# the port,
EXPOSE 8080
# the comand to run,
CMD ["./main"]